FROM node:18-bullseye-slim AS base

WORKDIR /usr/src/app

COPY ./package.json ./pnpm-lock.yaml /usr/src/app/

RUN corepack enable
RUN pnpm install

COPY ./ /usr/src/app

EXPOSE 3000

CMD [ "pnpm", "dev" ]