version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
    container_name: asc-api
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
      - ignore:/usr/src/app/node_modules/
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skru-asc

volumes:
  ignore: