version: '3.8'

services:
  api:
    build:
      context: .
      target: dev
    container_name: asc-api
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - web  
    command: pnpm dev

  db:
    image: postgres:15-alpine
    container_name: asc-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skru-asc
    volumes:
      - .db_data:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true